name: example
description: "Example demonstrating how to build a stateful widget simply."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0-131.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tasteful:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
