name: tasteful
description: a different take on stateful widgets.
homepage: https://github.com/yjbanov/tasteful

version: 0.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
